export const monstroHuntABI = [
  {
    type: 'function',
    name: 'createMonster',
    inputs: [
      { name: 'name', type: 'bytes32', internalType: 'bytes32' },
      { name: 'avatarId', type: 'uint8', internalType: 'uint8' },
      { name: 'tier', type: 'uint8', internalType: 'enum MonstroHunt.Tier' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'feedMonster',
    inputs: [{ name: 'monsterId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'huntMonster',
    inputs: [{ name: 'targetMonsterId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'sellMonster',
    inputs: [{ name: 'monsterId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getMonster',
    inputs: [{ name: 'monsterId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'name', type: 'bytes32', internalType: 'bytes32' },
      { name: 'avatarId', type: 'uint8', internalType: 'uint8' },
      { name: 'tier', type: 'uint8', internalType: 'enum MonstroHunt.Tier' },
      { name: 'initialWeight', type: 'uint256', internalType: 'uint256' },
      { name: 'weight', type: 'uint256', internalType: 'uint256' },
      { name: 'hungerDeadline', type: 'uint256', internalType: 'uint256' },
      { name: 'alive', type: 'bool', internalType: 'bool' },
      { name: 'lastRewardIndex', type: 'uint256', internalType: 'uint256' },
      { name: 'lastHuntAttemptAt', type: 'uint256', internalType: 'uint256' },
      { name: 'owner', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getOwnerMonsterId',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'isStarved',
    inputs: [{ name: 'monsterId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getFeedCost',
    inputs: [{ name: 'monsterId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPendingRewards',
    inputs: [{ name: 'monsterId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'canHunt',
    inputs: [
      { name: 'hunter', type: 'address', internalType: 'address' },
      { name: 'targetMonsterId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTotalMonsters',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'HUNGER_WINDOW',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'HUNT_COOLDOWN',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'MonsterCreated',
    inputs: [
      { name: 'monsterId', type: 'uint256', indexed: true },
      { name: 'owner', type: 'address', indexed: true },
      { name: 'name', type: 'bytes32', indexed: false },
      { name: 'avatarId', type: 'uint8', indexed: false },
      { name: 'tier', type: 'uint8', indexed: false },
      { name: 'initialWeight', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MonsterFed',
    inputs: [
      { name: 'monsterId', type: 'uint256', indexed: true },
      { name: 'feedCost', type: 'uint256', indexed: false },
      { name: 'newWeight', type: 'uint256', indexed: false },
      { name: 'newHungerDeadline', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MonsterHunted',
    inputs: [
      { name: 'monsterId', type: 'uint256', indexed: true },
      { name: 'hunter', type: 'address', indexed: true },
      { name: 'hunterReward', type: 'uint256', indexed: false },
      { name: 'distributedToAlive', type: 'uint256', indexed: false },
      { name: 'protocolFee', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'MonsterSold',
    inputs: [
      { name: 'monsterId', type: 'uint256', indexed: true },
      { name: 'owner', type: 'address', indexed: true },
      { name: 'payout', type: 'uint256', indexed: false },
      { name: 'protocolFee', type: 'uint256', indexed: false },
    ],
  },
] as const;
